name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to AWS server
      run: scp -o StrictHostKeyChecking=no -r ./* {{ secrets.USER }}@{{ secrets.SERVER }}:/service-config

    - name: Execute remote commands
      run: ssh -o StrictHostKeyChecking=no {{ secrets.USER }}@{{ secrets.SERVER }} << 'EOF'
        cd /service-config
        docker-compose down
        docker-compose pull
        docker-compose up -d
        EOF
